"""add meals table

Revision ID: 141aca9c0642
Revises: f83fe1b4e62a
Create Date: 2023-08-09 01:22:40.813127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141aca9c0642'
down_revision = 'f83fe1b4e62a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meals')
    # ### end Alembic commands ###
